# Generated by Django 5.0.3 on 2024-07-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.IntegerField(null=True),
        ),
    ]
